#stuff http://about.travis-ci.org/docs/

#Default test script = "npm test"
language: node_js

node_js:
  - 0.10

after_success:
  - chmod -R 777 coverage/copy_coverage_torepo.sh
  - coverage/copy_coverage_torepo.sh